version: '3.8'

services:
    orchestrator:
        build:
            context: ./OrchestratorMicroService
            dockerfile: OrchestratorMicroService.API/Dockerfile
        ports:
            - '5000:8080'
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - OrchestratorSettings__ExternalApiKey=YOUR-API-KEY-HERE
            - OrchestratorSettings__MinimumSuccessfulResponses=1
            - OrchestratorSettings__ProviderTimeoutMilliseconds=5000
            - ApiProviders__Api1BaseUrl=http://api1:8080/api
            - ApiProviders__Api2BaseUrl=http://api2:8080/api
            - ApiProviders__Api3BaseUrl=http://api3:8080/api
            - ApiProviders__ApiExternalBaseUrl=https://api.fastforex.io
        depends_on:
            - api1
            - api2
            - api3

    api1:
        container_name: rateoffersapi1
        build:
            context: ./RateOffersAPI1/RateOffersAPI1
            dockerfile: Dockerfile
        ports:
            - '5001:8080'
        environment:
            - ASPNETCORE_ENVIRONMENT=Development

    api2:
        container_name: rateoffersapi2
        build:
            context: ./RateOffersAPI2/RateOffersAPI2
            dockerfile: Dockerfile
        ports:
            - '5002:8080'
        environment:
            - ASPNETCORE_ENVIRONMENT=Development

    api3:
        container_name: rateoffersapi3
        build:
            context: ./RateOffersAPI3/RateOffersAPI3
            dockerfile: Dockerfile
        ports:
            - '5003:8080'
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
